APP_NAME="" # app directory Ex: your-app
APP_PATH="" # absolute path of the app Ex: /srv/your-app
GIT_REPO="" # ssh url of the git repo Ex: git@github.com:username/repo.git
SERVICES="" # deployed services in docker-compose.yml Ex: "backend,frontend"
VOLUMES="" # volumes name Ex: "volume1,volume2"
HEALTHCHECK_TIMEOUT=60 # in seconds
COMPOSENAME="" # name of the docker-compose.yml file

# DEV VARIABLES
APP_NAME_DEV="" # dev app directory Ex: your-app
APP_PATH_DEV="" # dev absolute path Ex: srv/your-app
SERVICES_DEV="" # dev services deployed Ex.: "backend_dev,frontend_dev"
VOLUMES_DEV="" # dev volumes Ex.: "volume1_dev" "volume2_dev"
COMPOSENAME_DEV="" # dev compose file dev docker-compose.yml